[workspace]
resolver = "2"

[package]
description = "System Update Tool"
edition = "2024"
include = [
  "Cargo.toml",
  "src/**/*"
]
name = "system_update_tool"
publish = false
rust-version = "1.90.0"
version = "1.0.0"

[[bin]]
name = "upt"
path = "src/main.rs"

